spring:
  application:
    name: AuthService
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 1028454795634-3k3455a2n8ute9t28kn2cqriimombg5k.apps.googleusercontent.com
              client-secret: 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
              scope:
                - email
                - profile
              redirect-uri: "https://apigatewayservice-1.onrender.com/auth/login/oauth2/code/{registrationId}"
              client-name: Google
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub


  datasource:
    url: jdbc:postgresql://localhost:5433/company
    username: postgres
    password: Abheysaini@1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka
